### ISSUE TITLE
Cannot compile when library is used in console application

### ISSUE THREAD

**Issue by zamronypj** [Xor-el/QRCodeGenLib4Pascal#2]
**Description**
When used in console application (using FreePascal only and without LCL), library refuse to compile due to dependency to Graphics unit.

**Expected behavior**
User should be able to use library for QR code generation in command line applicatioin similar how fcl-image is able to generate image in console application

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 16.04
 - Compiler Version FreePascal 3.0.4

**Comment by Xor-el** [comment]
Hi, as you have figured out, the library makes use of the graphics unit which is only available in the LCL that's why you are unable to compile it in a console app without LCL.
To be able to use it in an FPC console app without LCL, we have to use the fcl-image library which unfortunately I am unfamiliar with at the moment.
However, I am accepting patches from anyone to make this a possibility.

**Comment by Xor-el** [comment]
@zamronypj , I have implemented support for fcl-image in this library so it should compile without LCL.
I will appreciate it if you can test and confirm this.

**Comment by zamronypj** [comment]
@Xor-el I can confirm that library compile successfully in console application without LCL. Thank you.
